# tb/unit/envelope_follower/Makefile

TOP = envelope_follower_harness
G_PARAMS = -GSAMPLE_WIDTH=24 -GCOEFF_WIDTH=16 -GCOEFF_FRAC=16

F_FILES = rtl/filelists/dynamics/envelope_follower.f
SV_SRCS = tb/unit/envelope_follower/envelope_follower_harness.sv

CPP_TB = tb/unit/envelope_follower/tb.cpp

include ../unit.mk