# tb/unit/delay_line/Makefile

TOP = delay_line_harness

G_PARAMS = -GSAMPLE_WIDTH=24 -GGAIN_WIDTH=8
SV_SRCS  = rtl/interfaces/audio_stream_if.sv \
		   rtl/interfaces/wide_stream_if.sv \
           rtl/delay_line.sv

include ../unit.mk