# tb/unit/delay_line/Makefile

TOP = delay_line

G_PARAMS = -GWIDTH=24 -GDEPTH=2
SV_SRCS  = rtl/interfaces/audio_stream_if.sv \
		   rtl/interfaces/wide_stream_if.sv \
           rtl/delay_line.sv

CPP_TB   = tb/unit/delay_line/tb.cpp

include ../unit.mk