# tb/unit/saturator/Makefile

TOP = saturator_harness

G_PARAMS = -GSAMPLE_WIDTH=24
SV_SRCS  = -f rtl/iterfaces.f \
           rtl/saturator.sv \
           tb/unit/saturator/harness.sv

include ../unit.mk