# tb/unit/saturator/Makefile

TOP = saturator_harness
G_PARAMS = -GSAMPLE_WIDTH=24

F_FILES = rtl/filelists/saturator.f
SV_SRCS = tb/unit/saturator/saturator_harness.sv

CPP_TB   = tb/unit/saturator/tb.cpp

include ../unit.mk