# tb/unit/gate/Makefile

TOP = gate_harness
G_PARAMS = -GSAMPLE_WIDTH=24 -GCOEFF_WIDTH=16 -GCOEFF_FRAC=16 -GGAIN_WIDTH=17 -GGAIN_FRAC=16

F_FILES = rtl/filelists/dynamics/gate.f
SV_SRCS = tb/unit/gate/gate_harness.sv

CPP_TB = tb/unit/gate/tb.cpp

include ../unit.mk