# tb/unit/tapped_delay_line/Makefile

TOP = tapped_delay_line_harness
G_PARAMS = -GWIDTH=24 -GTAPS=4

F_FILES = rtl/filelists/tapped_delay_line.f
SV_SRCS = tb/unit/tapped_delay_line/tapped_delay_line_harness.sv

CPP_TB = tb/unit/tapped_delay_line/tb.cpp

include ../unit.mk