# tb/unit/fir/Makefile

TOP = fir_harness
G_PARAMS = -GSAMPLE_WIDTH=24 -GCOEFF_WIDTH=16 -GCOEFF_FRAC=15 -GGUARD_BITS=1 -GNUM_TAPS=8

F_FILES = rtl/filelists/fir.f
SV_SRCS = tb/unit/fir/fir_harness.sv

CPP_TB = tb/unit/fir/tb.cpp

include ../unit.mk