# tb/unit/volume_ctrl/Makefile

TOP = volume_ctrl_harness

G_PARAMS = -GSAMPLE_WIDTH=24 -GGAIN_WIDTH=8
SV_SRCS  = -f rtl/iterfaces.f \
           rtl/volume_ctrl.sv \
           tb/unit/volume_ctrl/harness.sv

include ../unit.mk