# tb/unit/audio_mux/Makefile
TOP      = audio_mux_harness
G_PARAMS = -GWIDTH=8 -GLATENCY=2

F_FILES  = rtl/filelists/audio_mux.f

SV_SRCS  = tb/unit/audio_mux/audio_mux_harness.sv
CPP_TB   = tb/unit/audio_mux/tb.cpp

include ../unit.mk